fix: fix pipeline#17 last (i hope)

diff --git a/.github/workflows/dev-ci-cd.yaml b/.github/workflows/dev-ci-cd.yaml
--- a/.github/workflows/dev-ci-cd.yaml
+++ b/.github/workflows/dev-ci-cd.yaml
@@ -106,13 +106,21 @@ jobs:
 
 
     steps:
+      - name: Verify compose file exists
+        run: |
+          echo "Current directory: $(pwd)"
+          echo "Files:"
+          ls -la
+          echo "Content of compose-dev.yaml:"
+          cat compose-dev.yaml || echo "File not found!"
+
       - name: Copy docker-compose file to server
         uses: appleboy/scp-action@v0.1.3
         with:
           host: ${{ secrets.DEV_SERVER_HOST }}
           username: ${{ secrets.DEV_SERVER_USER }}
           key: ${{ secrets.DEV_SERVER_SSH_KEY }}
-          source: "compose-dev.yaml"
+          source: "./compose-dev.yaml"
           target: "/home/akela/"
 
       - name: Deploy to development server
